DROP DATABASE IF EXISTS usuario_db;
DROP DATABASE IF EXISTS personaje_db;
DROP DATABASE IF EXISTS arma_db;
DROP DATABASE IF EXISTS tienda_db;
DROP DATABASE IF EXISTS pago_db;
DROP DATABASE IF EXISTS inventario_db;
DROP DATABASE IF EXISTS mision_db;
DROP DATABASE IF EXISTS ranking_db;
DROP DATABASE IF EXISTS combate_db;

CREATE DATABASE IF NOT EXISTS usuario_db;
CREATE DATABASE IF NOT EXISTS personaje_db;
CREATE DATABASE IF NOT EXISTS arma_db;
CREATE DATABASE IF NOT EXISTS tienda_db;
CREATE DATABASE IF NOT EXISTS pago_db;
CREATE DATABASE IF NOT EXISTS inventario_db;
CREATE DATABASE IF NOT EXISTS mision_db;
CREATE DATABASE IF NOT EXISTS ranking_db;
CREATE DATABASE IF NOT EXISTS combate_db;