CREATE DATABASE IF NOT EXISTS bd_usuarios
CREATE DATABASE IF NOT EXISTS tienda_db
CREATE DATABASE IF NOT EXISTS ranking_db
CREATE DATABASE IF NOT EXISTS personaje_db
CREATE DATABASE IF NOT EXISTS pago_db
CREATE DATABASE IF NOT EXISTS mision_db
CREATE DATABASE IF NOT EXISTS inventario_db
CREATE DATABASE IF NOT EXISTS combate_db

