spring:
  application:
    name: ranking-service
  config:
    import: "optional:configserver:http://localhost:8888"

---
# Perfil docker
spring:
  config:
    activate:
      on-profile: docker
    import: "optional:configserver:http://config-server:8888"
