spring:
  application:
    name: combate-service
  config:
    import: "optional:configserver:http://localhost:8888"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
---
# Perfil docker
spring:
  config:
    activate:
      on-profile: docker
    import: "optional:configserver:http://config-server:8888"